version: '3.8'

services:
  # 主应用服务
  wechat-passcode-service:
    build: .
    container_name: wechat-passcode-service
    environment:
      - REDIS_HOST=redis
    image: registry.cnbita.com:5000/lsy/wechat-passcode:v1
    ports:
      - "8080:8080"
    depends_on:
      - redis
    volumes:
      - ./logs:/app/logs
    networks:
      - wechat-network
    restart: unless-stopped

  # Redis缓存服务
  redis:
    image: registry.cnbita.com:5000/lsy/redis:7-alpine
    container_name: wechat-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - wechat-network
    restart: unless-stopped

volumes:
  redis_data:

networks:
  wechat-network:
    driver: bridge